import Feed from './index.js'
import async from 'async'


const feed = [
  {
    "title": "I Went On The Weirdest<br />Spring Break Trip You’ve<br/>Ever Heard Of",
    "author": "Andy Osmani",
    "avatar": "avatar0.jpg",
    "img": "feed0.jpg",
    "text": "<p>Picture this. You’ve got a few months left after seven long, (partly) grueling semesters at university.</p><p>You’re living in the heart of a city that’s known for its incredible weather — people would give a lot up to move to where you live.</p><p>You’ve grown up in cities where the weather was more often than not just… perfect. Never too hot, never too cold, 365 days a year, 7 days a week, 24 hours a day, 60 minutes a… well, you get the point.</p><p>And… you’ve got your last spring break as an undergraduate coming up.</p><p>Spring break!</p><p>A time that’s borderline sacred with traditions that are meant to be kept — traditions that dictate that you, an undergraduate at a university in the United States of America, are meant to spend in the balmy, warm weather of a country south of the border where most rules seldom matter, most grub is dirt cheap, and if you’re dressed in anything but board shorts or a bikini people look at you like you’ve just swam ashore from a sunken ship that was meant to leave from Seattle to Alaska but had an intoxicated skipper who couldn’t tell north from south and sunk his ship off the coast of Mexico.</p><p>It really is a tradition at this point — going to Cabo (Tijuana if you’re stingy) for spring break. Which is why I was, well, baffled at the simple fact that it didn’t take too much time to convince three friends to join me on what is quite possibly the weirdest vacation you’ve ever heard of — a vacation to — wait for it — Fort McMurray. Which is in northern Alberta. Which is in Canada.</p><p>We were in Los Angeles, we could have gone anywhere, and we didn’t just go to Canada, we didn’t just go to Alberta — we went to Fort McMurray.</p>"
  },
  {
    "title": "Thoughts from Taiwan",
    "author": "TJ Holowaychuk",
    "avatar": "avatar1.jpg",
    "img": "feed1.jpg",
    "text": "<p>This was the first trip to Taiwan for me and my sister in which we weren’t escorted by family. We had to find our own way this time, which made for a richer experience. We interacted more with locals. Our Chinese improved by virtue of having to communicate with others and needing to recognize characters in place names and menu items.</p><p>My newfound hobby of running let me explore Taiwan’s landscape on my own in the early mornings. I ran at the local elementary school track in Yizhu, on the streets of the Shilin and Neihu districts of Taipei, and up Elephant Mountain to catch the sunrise over Taipei 101. The only other people that were up at that hour were old folks who were also exercising. They greeted me good morning in Taiwanese and I greeted them back and I felt like I had been inducted into their secret club. I love the feeling of being awake while everyone else is still sleeping.</p><p>Where you live matters. And you can choose where you live. So why not love where you live? I can pretty easily pack my belongings (which aren’t really that much), move to another city, find a job, make friends, and start a new life. Taipei is a particularly great city. The cost of living (food, housing, transportation) is relatively low. And its urban planning and design is impressive—public transportation is efficient and accessible; public spaces, like parks and basketball courts, are abundant; facilities are well-maintained. We took advantage of the popular city bike share program, YouBike, to zip from place to place as well as take in the sights.</p><p>Everywhere we went, people (be it family, family friends, or friends of family friends) went out of their way to make us feel comfortable. I even felt undeserving of such generosity. They picked us up. They drove us places. They let us stay at their homes. And when we left, they suggested we stay longer. And, of course, they offered us food. So much food. It was all very much appreciated and I can’t thank them enough. I won’t hesitate to offer the same level of hospitality to anyone that visits me in the future.</p><p>Food was the overarching theme of the trip. All of my most memorable experiences and interactions have revolved around it, from local breakfast shops, self-serve buffets, and night markets to elaborate lunches and dinners with family and friends. It was all so delicious and inspiring. I will be cooking only Taiwanese food for the next few months.</p>"
  },
  {
    "title": "Tro Tro Trip",
    "author": "Dan Abramov",
    "avatar": "avatar2.jpg",
    "img": "feed2.jpg",
    "text": "<p>Over the weekend we made a two hour visit to a village called Aburi in hot and sticky ‘tro tros’. A ‘tro tro’ is a Ghanaian bus which cost around 1 Cedes 50 Pesewas, around 70p in English sterling.</p><p>On the route there, we saw three funeral processions along the roadside. In Ghana, funerals happen over a period of three days, starting on a Sunday, and include whole villages and people from a wide region, who wear red and black.</p><p>The first stop was the Botanical Gardens where we eventually found the famous 150 year old tree with webbed trunk. There was a wedding being prepared and a traditional church celebration taking place. We ventured down various paths and encountered giant African millipedes and multiple lizards. We also met another English group from London who took this photo of us in an abandoned helicopter in the middle of the gardens!</p><p>The next stop was the Boti waterfalls, the second largest waterfalls in Ghana, with a 33m drop! We ate Plantain crisps as we climbed down 250 steps to the wonderful waterfalls and paddled in the refreshing water at the end.</p><p>While we were paddling in the waterfall, Megan was proposed to by a Ghanaian man and had to create a boyfriend to divert attention so he just took a photo as a memento instead!!</p><p>Tomorrow we are back to teaching for the morning and then we plan to visit the art museum in the afternoon, which is in the centre of Accra, a 20 minute ‘tro tro’ ride away.</p>"
  },
  {
    "title": "2 days. 36 miles. One epic adventure in the wilderness of Washington.",
    "author": "Paul Miller",
    "avatar": "avatar3.jpg",
    "img": "feed3.jpg",
    "text": "<p>August 8th, 2014: Andrew and I started from Redmond, Washington towards the Three Fingers Lookout trailhead. It was just early enough- right after dawn — to see the halos of fog that had formed above fields on our way to Mountain Loop Highway.</p><p>Back in April, 2014 when I was obsessing over all the nature sauntering I could do during my upcoming summer in Washington (I had accepted a 3 month internship at Xbox), I came across Backpacker magazine’s month of March issue that was dedicated to one of America’s most underrated expanse of wilderness- the North Cascades. Among some of the outstanding hikes cherry picked for this issue, there was one that stood out and captivated me instantly — it illustrated a lookout on Mt. Three Fingers as its one-way culmination (see cover below) & I made up mind that this summer I was going to get up to where those guys where standing by hook or by crook.</p><p>In 1931 the southernmost spire of the Three Fingers (which had never been summited) was flattened using dynamite. Thereafter, like the pyramids of Egypt, human and mule suffering sustained this undertaking and the lookout stood tall in the same year, promising to shield this paradise from forest fires as a vantage alert system. After a respectable 10 years it was retired for use as a fire lookout & it decayed for the next 30 before being restored by Everett Mountaineers, an outdoor recreation club in the Pacific Northwest who proudly maintain it to date. If Muir were alive, he’d be so proud of their work and dedication for conserving this place so it can be accessible for both current and future generations.</p><p>Google it. One look at the images that pop up will make you squirm with disbelief- how the heck did they build that all the way up there in 1931? Even today, in 2014, it seems almost insane to engineer the process of building a lookout, if anything there. At the same time it will fill your imagination with wonder and force you to compare it with an archetypal Eagle’s Nest. Whether you compare its location to the fortress in the high alps depicted in the epic World War II movie Where Eagles Dare or if you think of it as the perfect setting for an evil scientist’s lair, one thing remains true- it exists and you can get to it.</p><p>Pugetoplis’ affliction for open country kept it from withering away and the trail leading to it soon became a favorite of hikers who wanted to enter the realm of technical climbing. The 16 mile round trip journey was worth braving the exposed snowfields and ridges to get to this shrine and experience it’s history and beauty.</p>"
  },
  {
    "title": "Traveling to Sky Pic",
    "author": "Eric Bidelman",
    "avatar": "avatar4.jpg",
    "img": "feed4.jpg",
    "text": "<p>This was the first trip to Taiwan for me and my sister in which we weren’t escorted by family. We had to find our own way this time, which made for a richer experience. We interacted more with locals. Our Chinese improved by virtue of having to communicate with others and needing to recognize characters in place names and menu items.</p><p>My newfound hobby of running let me explore Taiwan’s landscape on my own in the early mornings. I ran at the local elementary school track in Yizhu, on the streets of the Shilin and Neihu districts of Taipei, and up Elephant Mountain to catch the sunrise over Taipei 101. The only other people that were up at that hour were old folks who were also exercising. They greeted me good morning in Taiwanese and I greeted them back and I felt like I had been inducted into their secret club. I love the feeling of being awake while everyone else is still sleeping.</p><p>Where you live matters. And you can choose where you live. So why not love where you live? I can pretty easily pack my belongings (which aren’t really that much), move to another city, find a job, make friends, and start a new life. Taipei is a particularly great city. The cost of living (food, housing, transportation) is relatively low. And its urban planning and design is impressive—public transportation is efficient and accessible; public spaces, like parks and basketball courts, are abundant; facilities are well-maintained. We took advantage of the popular city bike share program, YouBike, to zip from place to place as well as take in the sights.</p><p>Everywhere we went, people (be it family, family friends, or friends of family friends) went out of their way to make us feel comfortable. I even felt undeserving of such generosity. They picked us up. They drove us places. They let us stay at their homes. And when we left, they suggested we stay longer. And, of course, they offered us food. So much food. It was all very much appreciated and I can’t thank them enough. I won’t hesitate to offer the same level of hospitality to anyone that visits me in the future.</p><p>Food was the overarching theme of the trip. All of my most memorable experiences and interactions have revolved around it, from local breakfast shops, self-serve buffets, and night markets to elaborate lunches and dinners with family and friends. It was all so delicious and inspiring. I will be cooking only Taiwanese food for the next few months.</p>"
  },
  {
    "title": "Awesome Trip to Heart of Asia",
    "author": "Arthur Verschaeve",
    "avatar": "avatar5.jpg",
    "img": "feed5.jpg",
    "text": "<p>This was the first trip to Taiwan for me and my sister in which we weren’t escorted by family. We had to find our own way this time, which made for a richer experience. We interacted more with locals. Our Chinese improved by virtue of having to communicate with others and needing to recognize characters in place names and menu items.</p><p>My newfound hobby of running let me explore Taiwan’s landscape on my own in the early mornings. I ran at the local elementary school track in Yizhu, on the streets of the Shilin and Neihu districts of Taipei, and up Elephant Mountain to catch the sunrise over Taipei 101. The only other people that were up at that hour were old folks who were also exercising. They greeted me good morning in Taiwanese and I greeted them back and I felt like I had been inducted into their secret club. I love the feeling of being awake while everyone else is still sleeping.</p><p>Where you live matters. And you can choose where you live. So why not love where you live? I can pretty easily pack my belongings (which aren’t really that much), move to another city, find a job, make friends, and start a new life. Taipei is a particularly great city. The cost of living (food, housing, transportation) is relatively low. And its urban planning and design is impressive—public transportation is efficient and accessible; public spaces, like parks and basketball courts, are abundant; facilities are well-maintained. We took advantage of the popular city bike share program, YouBike, to zip from place to place as well as take in the sights.</p><p>Everywhere we went, people (be it family, family friends, or friends of family friends) went out of their way to make us feel comfortable. I even felt undeserving of such generosity. They picked us up. They drove us places. They let us stay at their homes. And when we left, they suggested we stay longer. And, of course, they offered us food. So much food. It was all very much appreciated and I can’t thank them enough. I won’t hesitate to offer the same level of hospitality to anyone that visits me in the future.</p><p>Food was the overarching theme of the trip. All of my most memorable experiences and interactions have revolved around it, from local breakfast shops, self-serve buffets, and night markets to elaborate lunches and dinners with family and friends. It was all so delicious and inspiring. I will be cooking only Taiwanese food for the next few months.</p>"
  },
  {
    "title": "Sky Pic of Dream",
    "author": "Ingvar Stepanyan",
    "avatar": "avatar6.jpg",
    "img": "feed6.jpg",
    "text": "<p>Picture this. You’ve got a few months left after seven long, (partly) grueling semesters at university.</p><p>You’re living in the heart of a city that’s known for its incredible weather — people would give a lot up to move to where you live.</p><p>You’ve grown up in cities where the weather was more often than not just… perfect. Never too hot, never too cold, 365 days a year, 7 days a week, 24 hours a day, 60 minutes a… well, you get the point.</p><p>And… you’ve got your last spring break as an undergraduate coming up.</p><p>Spring break!</p><p>A time that’s borderline sacred with traditions that are meant to be kept — traditions that dictate that you, an undergraduate at a university in the United States of America, are meant to spend in the balmy, warm weather of a country south of the border where most rules seldom matter, most grub is dirt cheap, and if you’re dressed in anything but board shorts or a bikini people look at you like you’ve just swam ashore from a sunken ship that was meant to leave from Seattle to Alaska but had an intoxicated skipper who couldn’t tell north from south and sunk his ship off the coast of Mexico.</p><p>It really is a tradition at this point — going to Cabo (Tijuana if you’re stingy) for spring break. Which is why I was, well, baffled at the simple fact that it didn’t take too much time to convince three friends to join me on what is quite possibly the weirdest vacation you’ve ever heard of — a vacation to — wait for it — Fort McMurray. Which is in northern Alberta. Which is in Canada.</p><p>We were in Los Angeles, we could have gone anywhere, and we didn’t just go to Canada, we didn’t just go to Alberta — we went to Fort McMurray.</p>"
  },
  {
    "title": "Weekend Balloon Trip",
    "author": "Evan You",
    "avatar": "avatar7.jpg",
    "img": "feed7.jpg",
    "text": "<p>August 8th, 2014: Andrew and I started from Redmond, Washington towards the Three Fingers Lookout trailhead. It was just early enough- right after dawn — to see the halos of fog that had formed above fields on our way to Mountain Loop Highway.</p><p>Back in April, 2014 when I was obsessing over all the nature sauntering I could do during my upcoming summer in Washington (I had accepted a 3 month internship at Xbox), I came across Backpacker magazine’s month of March issue that was dedicated to one of America’s most underrated expanse of wilderness- the North Cascades. Among some of the outstanding hikes cherry picked for this issue, there was one that stood out and captivated me instantly — it illustrated a lookout on Mt. Three Fingers as its one-way culmination (see cover below) & I made up mind that this summer I was going to get up to where those guys where standing by hook or by crook.</p><p>In 1931 the southernmost spire of the Three Fingers (which had never been summited) was flattened using dynamite. Thereafter, like the pyramids of Egypt, human and mule suffering sustained this undertaking and the lookout stood tall in the same year, promising to shield this paradise from forest fires as a vantage alert system. After a respectable 10 years it was retired for use as a fire lookout & it decayed for the next 30 before being restored by Everett Mountaineers, an outdoor recreation club in the Pacific Northwest who proudly maintain it to date. If Muir were alive, he’d be so proud of their work and dedication for conserving this place so it can be accessible for both current and future generations.</p><p>Google it. One look at the images that pop up will make you squirm with disbelief- how the heck did they build that all the way up there in 1931? Even today, in 2014, it seems almost insane to engineer the process of building a lookout, if anything there. At the same time it will fill your imagination with wonder and force you to compare it with an archetypal Eagle’s Nest. Whether you compare its location to the fortress in the high alps depicted in the epic World War II movie Where Eagles Dare or if you think of it as the perfect setting for an evil scientist’s lair, one thing remains true- it exists and you can get to it.</p><p>Pugetoplis’ affliction for open country kept it from withering away and the trail leading to it soon became a favorite of hikers who wanted to enter the realm of technical climbing. The 16 mile round trip journey was worth braving the exposed snowfields and ridges to get to this shrine and experience it’s history and beauty.</p>"

  }
]

export default (cb) => Feed.removeItems(() =>
  async.each(feed, (post, callback) => {
    Feed.addValue(post, (err, post) => {
      console.log(post)
      callback()
    })
  }, err => cb(err))
)
